### ISSUE TITLE
Support for maize Zm-B73-REFERENCE-NAM-5.0

### ISSUE THREAD

**Issue by lipc20052006** [VIB-PSB/MINI-EX#11]
Is it possible to support for maize Zm-B73-REFERENCE-NAM-5.0？or provide the method to produce annotation file in data_zma?

Thank you very much.

**Comment by SvitlanaLukicheva** [comment]
Dear @lipc20052006 , we well add the data for Zm-B73-REFERENCE-NAM-5.0 in early August.

**Comment by SvitlanaLukicheva** [comment]
Dear @lipc20052006 , the support for Zm-B73-REFERENCE-NAM-5.0 was added in the latest release (v2.1).
