### ISSUE TITLE
Error executing process > 'unzip_motifMappings'

### ISSUE THREAD

**Issue by gabimadrid** [VIB-PSB/MINI-EX#8]
Hi, I'm trying to use MINIEX for my analysis but I run into an error trying the example. Can you help me with it? 
I downloaded the repository directly from GitHub to my cluster so not sure what could be missing
The error is:
Error executing process > 'unzip_motifMappings'

Caused by:
  java.io.IOException: Cannot run program "qsub" (in directory "/blue/mresende/share/gmadrid/MINIEX/MINI-EX/work/bb/d950bab0b71245a580a521aa9041cb"): error=2, No such file or directory

Here's the full info:

N E X T F L O W  ~  version 22.11.1-edge
Launching `miniex.nf` [sharp_roentgen] DSL2 - revision: f3e1492824
      Motif-Informed Network Inference from gene EXpression
      =====================================================
Running TF motif enrichment filtering on  TF-F_motifs
      Running single-cell cluster enrichment using the top 700 upregulated genes per cluster
      Filtering out regulons of single-cell clusters where the TF is expressed in less than 10 % of the cells
Plotting expression specificity and DE calls for the top 150 regulons

[-        ] process > run_grnboost         [  0%] 0 of 1
[-        ] process > unzip_motifMappings  [  0%] 0 of 1
[-        ] process > run_enricher_motifs  -
[-        ] process > filter_motifs        -
[-        ] process > run_grnboost         [  0%] 0 of 1
[bb/d950ba] process > unzip_motifMappings  [100%] 1 of 1, failed: 1
[-        ] process > run_enricher_motifs  -
[-        ] process > filter_motifs        -
[-        ] process > get_topDEGs          [  0%] 0 of 1
[-        ] process > run_enricher_cluster -
[-        ] process > filter_expression    -
[-        ] process > make_info_file       -
[-        ] process > clustermap_regs      -
[-        ] process > network_centrality   -
[-        ] process > getFiles_enrichment  -
[-        ] process > GO_enricher          -
[-        ] process > check_reference      -
[-        ] process > ranking_df_ref       -
[-        ] process > makeBorda            -
[-        ] process > heatmap_tops         -
Error executing process > 'unzip_motifMappings'

Caused by:
  java.io.IOException: Cannot run program "qsub" (in directory "/blue/mresende/share/gmadrid/MINIEX/MINI-EX/work/bb/d950bab0b71245a580a521aa9041cb"): error=2, No such file or directory

Command executed:

  qsub -terse .command.run

Command exit status:
  -

Command output:
  (empty)

**Comment by gabimadrid** [comment]
FYI 
So for everyone not using SGE, remember to change the config file for whatever job scheduler if running in a cluster  👍

**Comment by e-tomato** [comment]
Hi @gabimadrid,

Sorry to open this issue again. I met the same issue as mentioned above. I'm currently running this program in a HPC cluster with slurm.  

How can I change the config file if I'm not using SGE cluster? could you show an example?  Thank you.

Error message: 
> Error executing process > 'run_grnboost (1)'
> 
> Caused by:
>   Cannot run program "qsub" (in directory "/work/hguojian/snRNA-seq/MINI-EX/MINI-EX/work/b4/b1e0bfb9cace26b8776c32d324ad5d"): error=2, No such file or directory
> 
> Command executed:
> 
>   qsub -terse .command.run
> 
> Command exit status:
>   -
> 
> Command output:
>   (empty)
>

**Comment by SvitlanaLukicheva** [comment]
Dear @e-tomato ,

If you are using SLURM, then you can set `name` to `'slurm'` (instead of `'sge'`) in the following block of the config file (miniex.config):
```
executor {
    name = 'sge'
    queueSize = 5
}
```

You can find a detailed documentation about the SLURM executor [here](https://www.nextflow.io/docs/latest/executor.html#slurm).

**Comment by e-tomato** [comment]
I appreciate your quick reply.

I encountered another error after replacing "sge" with "slurm".  Could it be due to some missing unloaded modules with slurm?  if this is the case, which modules should I load first?   Thank you. 

**The modules I have loaded:** 
module load bioinfo/Nextflow-v19.10.0
module load system/singularity-3.7.3

**Error message:** 
> Error executing process > 'get_topDEGs (1)'
> 
> Caused by:
>   Failed to submit process to grid scheduler for execution
> 
> Command executed:
> 
>   sbatch .command.run
> 
> Command exit status:
>   255
> 
> Command output:
>   sbatch: invalid option -- 'l'
>   Try "sbatch --help" for more information
> 
>

**Comment by SvitlanaLukicheva** [comment]
Dear @e-tomato ,

I think this error occurs because other cluster-specific options are still configured for a SGE executor. You can check the last part of the config file (everything after `process`) and adapt SGE cluster options to the SLURM syntax.

**Comment by e-tomato** [comment]
Dear @SvitlanaLukicheva,

The following is the config file:
executor {
    name = 'slurm'
    queueSize = 5
}

process.container = "vibpsb/mini-ex:latest"
singularity {
    enabled = true
    cacheDir = "singularity_cache"
    autoMounts = true
}

params {
        expressionMatrix = "$baseDir/tomato/INPUTS/*_matrix.txt"
        markersOut = "$baseDir/tomato/INPUTS/*_allMarkers.txt"
        cell2clusters = "$baseDir/tomato/INPUTS/*_cells2clusters.txt"
        cluster2ident = "$baseDir/tomato/INPUTS/*_identities.txt"
        TF_list = "$baseDir/tomato/INPUTS/TF_list.txt"
        termsOfInterest = null
//      termsOfInterest = "$baseDir/tomato/INPUTS/GOsIwant.txt"

        grnboostOut = null
//      grnboostOut = "/$baseDir/tomato/OUTPUTS/GRNBoost2_output/*_grnboost2.txt"

        featureFile_motifs = "$baseDir/data_sly/sly_2023.1_motifMapping.out.gz"
        infoTF = "$baseDir/data_sly/sly_TF2fam2mot.txt"
        GOfile = "$baseDir/data_sly/sly_go_gene_plaza_all_filt1k_extended_bp_noBP.txt"
        alias = "$baseDir/data_sly/sly_gene_aliases.txt"

        script_enricher = "$baseDir/bin/enricherv2.4"
        script_grnboost = "$baseDir/bin/MINIEX_grnboostMultiprocess.py"
        script_motifs = "$baseDir/bin/MINIEX_filterForMotifs.py"
        script_topDEGs = "$baseDir/bin/MINIEX_selectTopDEGs.py"
        script_expTFs = "$baseDir/bin/MINIEX_filterForTFExp.py"
        script_info = "$baseDir/bin/MINIEX_makeInfoFile.py"
        script_clustermap = "$baseDir/bin/MINIEX_clustermap.py"
        script_networkCentrality = "$baseDir/bin/MINIEX_network_analysis.py"
        script_checkReference = "$baseDir/bin/MINIEX_checkRef.py"
        script_filesEnrichment = "$baseDir/bin/MINIEX_makeFilesEnrichment.py"
        script_makedfRef = "$baseDir/bin/MINIEX_makeRankingDf_ref.py"
        script_makedfStd = "$baseDir/bin/MINIEX_makeRankingDf_std.py"
        script_makeborda = "$baseDir/bin/MINIEX_makeBorda.py"
        script_heatmapTops = "$baseDir/bin/MINIEX_visual_heatmap_top150.py"

        tops = "700"
        expressionFilter = "10"
        motifFilter = "TF-F_motifs"
        topRegs = "150"
}

process {
    withName: run_grnboost {
        clusterOptions = '-l h_vmem=15G -pe <pe_name> 5'
    }
    withName: unzip_motifMappings {
        clusterOptions = '-l h_vmem=2G'
    }
    withName: run_enricher_motifs {
        clusterOptions = '-l h_vmem=4G'
    }
    withName: filter_motifs {
        clusterOptions = '-l h_vmem=20G'
    }
    withName: get_topDEGs {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: run_enricher_cluster {
        clusterOptions = '-l h_vmem=4G'
    }
    withName: filter_expression {
        clusterOptions = '-l h_vmem=20G'
    }
        withName: make_info_file {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: network_centrality {
        clusterOptions = '-l h_vmem=20G'
    }
    withName: getFiles_enrichment {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: GO_enricher {
        clusterOptions = '-l h_vmem=4G'
    }
        withName: check_reference {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: ranking_df_ref {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: ranking_df_std {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: makeBorda {
        clusterOptions = '-l h_vmem=10G'
    }
    withName: heatmap_tops {
        clusterOptions = '-l h_vmem=20G'
    }
    withName: clustermap_regs {
        clusterOptions = '-l h_vmem=20G'
    }
}

**Comment by SvitlanaLukicheva** [comment]
Yes, you should update everything in the `process` part (the part below) to make it compatible with the SLURM syntax.

```
process {
withName: run_grnboost {
clusterOptions = '-l h_vmem=15G -pe <pe_name> 5'
}
withName: unzip_motifMappings {
clusterOptions = '-l h_vmem=2G'
}
withName: run_enricher_motifs {
clusterOptions = '-l h_vmem=4G'
}
withName: filter_motifs {
clusterOptions = '-l h_vmem=20G'
}
withName: get_topDEGs {
clusterOptions = '-l h_vmem=10G'
}
withName: run_enricher_cluster {
clusterOptions = '-l h_vmem=4G'
}
withName: filter_expression {
clusterOptions = '-l h_vmem=20G'
}
withName: make_info_file {
clusterOptions = '-l h_vmem=10G'
}
withName: network_centrality {
clusterOptions = '-l h_vmem=20G'
}
withName: getFiles_enrichment {
clusterOptions = '-l h_vmem=10G'
}
withName: GO_enricher {
clusterOptions = '-l h_vmem=4G'
}
withName: check_reference {
clusterOptions = '-l h_vmem=10G'
}
withName: ranking_df_ref {
clusterOptions = '-l h_vmem=10G'
}
withName: ranking_df_std {
clusterOptions = '-l h_vmem=10G'
}
withName: makeBorda {
clusterOptions = '-l h_vmem=10G'
}
withName: heatmap_tops {
clusterOptions = '-l h_vmem=20G'
}
withName: clustermap_regs {
clusterOptions = '-l h_vmem=20G'
}
```

**Comment by gabimadrid** [comment]
Yeah, same as @SvitlanaLukicheva said. You need to “translate” it to slurm
